### PR TITLE
Reconnect session on resume from sleep

### PR DESCRIPTION
**Pull request by nowrep**
Stop session before going to sleep and try to reconnect on resume from sleep.

### CODE REVIEW

**Comment by streetpea** [comment]
another thing to note is that you can get a remote play is in use error if you reconnect too quickly (before the remote play server has a chance to shut down ... when I tested this out I noticed that and adding `--system-talk-name=org.freedesktop.login1` seems sufficient instead of the whole system bus (at least turning my console to sleep and turning back on resulted in the console reconnecting).

**Comment by nowrep** [comment]
> another thing to note is that you can get a remote play is in use error if you reconnect too quickly

Yeah that already happens when just trying to connect right after disconnecting. But for me that 10s is enough for it to succeed eventually (maybe if needed it can be increased to 15s?). Also it should definitely not be an issue when putting deck to sleep as the session is stopped before going to sleep and then it takes additional time to finish sleep -> resume before it stars to connect to console.

**Comment by streetpea** [comment]
If the console goes to sleep after the Steam Deck sleeps (for example power saving settings on the PS5 are on and a certain amount of time has passed causing the PS5 to enter sleep mode [can manually put the ps5 in sleep mode for testing purposes]) this will fail. May want to check if the PS5 is ready and if not wakeup first.

**Comment by nowrep** [comment]
> ... this will fail

And that's fine, there is multiple other reasons why it can fail. 

> May want to check if the PS5 is ready and if not wakeup first.

Can't really do that because it requires discovery response which may not be ready at the time for various reasons. The wakeup packet could be unconditionally sent in `StreamSession::Start()` but not sure if good idea.

**Comment by nowrep** [comment]
Wakeup works now.

**Comment by streetpea** [comment]
The discovery manager uses broadcast and so it only seems to work for local connections so this version of wakeup will likely only work for local connections not remote. That's fine as a limitation though.

**Pull request merged**
