### PR TITLE
Add Apple Silicon arm64 build

### PR DESCRIPTION
**Pull request by outcoldman**
@nowrep I hope I did everything right, I have not merged your changes of copying other libraries, etc. Just added a build of arm64 as a second job in that workflow. Hope I did everything right 🤞

### CODE REVIEW

**Comment by nowrep** [comment]
Cherry-pick my commit from the other PR and then make changes on top of it please.

**Comment by outcoldman** [comment]
@nowrep done, I have not verified the build yet, hope that MoltenVK library has both versions (arm64 and intel)

**Comment by nowrep** [comment]
It should be universal binary.

**Comment by outcoldman** [comment]
@nowrep just verified the build, everything works! And sorry, did not get, do you want me to make a universal binary? Or do you say that MoltenVK is universal?

**Pull request merged**
