### PR TITLE
QML Gui

### PR DESCRIPTION
**Pull request by nowrep**
* Better touch controls
* Controller navigation support
* Stream menu
* Steam on-screen keyboard integration (Game mode + Desktop mode)
* Everything in one window, no extra windows for dialogs
* Windows and macOS support ? (untested)

### CODE REVIEW

**Comment by nowrep** [comment]
Ready now.

**Comment by nowrep** [comment]
Stream menu, opened with <kbd>Ctrl+O</kbd>. On Deck maybe it can be mapped to right trackpad?

**Comment by HamzaM** [comment]
That looks really good !

**Comment by antonpolskiy** [comment]
Hi! Great work! I know I'm late but I also had an attempt to make some gamepad friendly UI. There is still a lot of work to be done because it was made just as a prototype. Also there is no  register and settings windows yet.
[my branch](https://github.com/antonpolskiy/chiaki4deck/tree/gamepad-ui  )
[assets I made and prototype](https://www.figma.com/file/aEWlQogRhHmMWfKHy7dwex/Untitled?type=design&node-id=91%3A876&mode=design&t=l9GXLe5HZ7LT4qtu-1)
PS. It needs heavy refactoring.
2023-12-30-120449_1284x828_escrotum
2023-12-30-120458_1284x828_escrotum
2023-12-30-120501_1284x828_escrotum
2023-12-30-120515_1284x748_escrotum
2023-12-30-120553_1284x828_escrotum

**Pull request merged**
